version: "3.9"

services:
  serviceregistry:
    build: 
      context: ..
      dockerfile: build/serviceregistry.Dockerfile
    stdin_open: true
    tty: true     

  node:
    build:
      context: ..
      dockerfile: build/node.Dockerfile
    depends_on:
      serviceregistry:
         condition: service_started
    stdin_open: true
    tty: true
    deploy: 
      mode: replicated
      replicas: 4


