version: "3.9"

services:
  serviceregistry:
    hostname: serviceregistry
    container_name: serviceregistry
    build: 
      context: ./serviceregistry
      dockerfile: serviceregistry/Dockerfile
    stdin_open: true
    tty: true

  node:
    build:
      context: ./node
      dockerfile: node/Dockerfile
    depends_on:
      - serviceregistry
    stdin_open: true
    tty: true
    deploy: 
      mode: replicated
      replicas: 4
