version: "3.9"

services:
  serviceregistry:
    hostname: serviceregistry
    container_name: serviceregistry
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:40042:40042
    stdin_open: true
    tty: true

#  node:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - serviceregistry
#    stdin_open: true
#    tty: true
#    deploy: 
#      mode: replicated
#      replicas: 4
