version: "3.9"

services:
  serviceregistry:
#    hostname: serviceregistry
#    container_name: serviceregistry
    build: 
      context: .
      dockerfile: serviceregistry.Dockerfile
    stdin_open: true
    tty: true     

  node:
#    container_name: node
    build:
      context: .
      dockerfile: node.Dockerfile
    depends_on:
      serviceregistry:
         condition: service_started
    stdin_open: true
    tty: true
    deploy: 
      mode: replicated
      replicas: 4


