// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node/protonode.proto

package node

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Node struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	ActualNextFailed     bool     `protobuf:"varint,4,opt,name=actualNextFailed,proto3" json:"actualNextFailed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e2dc367da0f1a31, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Node) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Node) GetActualNextFailed() bool {
	if m != nil {
		return m.ActualNextFailed
	}
	return false
}

type NodeAddr struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeAddr) Reset()         { *m = NodeAddr{} }
func (m *NodeAddr) String() string { return proto.CompactTextString(m) }
func (*NodeAddr) ProtoMessage()    {}
func (*NodeAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e2dc367da0f1a31, []int{1}
}

func (m *NodeAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeAddr.Unmarshal(m, b)
}
func (m *NodeAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeAddr.Marshal(b, m, deterministic)
}
func (m *NodeAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeAddr.Merge(m, src)
}
func (m *NodeAddr) XXX_Size() int {
	return xxx_messageInfo_NodeAddr.Size(m)
}
func (m *NodeAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeAddr.DiscardUnknown(m)
}

var xxx_messageInfo_NodeAddr proto.InternalMessageInfo

func (m *NodeAddr) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *NodeAddr) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type NodeId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeId) Reset()         { *m = NodeId{} }
func (m *NodeId) String() string { return proto.CompactTextString(m) }
func (*NodeId) ProtoMessage()    {}
func (*NodeId) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e2dc367da0f1a31, []int{2}
}

func (m *NodeId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeId.Unmarshal(m, b)
}
func (m *NodeId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeId.Marshal(b, m, deterministic)
}
func (m *NodeId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeId.Merge(m, src)
}
func (m *NodeId) XXX_Size() int {
	return xxx_messageInfo_NodeId.Size(m)
}
func (m *NodeId) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeId.DiscardUnknown(m)
}

var xxx_messageInfo_NodeId proto.InternalMessageInfo

func (m *NodeId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Election struct {
	Starter              int32    `protobuf:"varint,1,opt,name=starter,proto3" json:"starter,omitempty"`
	Delay                float32  `protobuf:"fixed32,2,opt,name=delay,proto3" json:"delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Election) Reset()         { *m = Election{} }
func (m *Election) String() string { return proto.CompactTextString(m) }
func (*Election) ProtoMessage()    {}
func (*Election) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e2dc367da0f1a31, []int{3}
}

func (m *Election) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Election.Unmarshal(m, b)
}
func (m *Election) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Election.Marshal(b, m, deterministic)
}
func (m *Election) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Election.Merge(m, src)
}
func (m *Election) XXX_Size() int {
	return xxx_messageInfo_Election.Size(m)
}
func (m *Election) XXX_DiscardUnknown() {
	xxx_messageInfo_Election.DiscardUnknown(m)
}

var xxx_messageInfo_Election proto.InternalMessageInfo

func (m *Election) GetStarter() int32 {
	if m != nil {
		return m.Starter
	}
	return 0
}

func (m *Election) GetDelay() float32 {
	if m != nil {
		return m.Delay
	}
	return 0
}

type Ok struct {
	Starter              int32    `protobuf:"varint,1,opt,name=starter,proto3" json:"starter,omitempty"`
	Delay                float32  `protobuf:"fixed32,2,opt,name=delay,proto3" json:"delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ok) Reset()         { *m = Ok{} }
func (m *Ok) String() string { return proto.CompactTextString(m) }
func (*Ok) ProtoMessage()    {}
func (*Ok) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e2dc367da0f1a31, []int{4}
}

func (m *Ok) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ok.Unmarshal(m, b)
}
func (m *Ok) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ok.Marshal(b, m, deterministic)
}
func (m *Ok) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ok.Merge(m, src)
}
func (m *Ok) XXX_Size() int {
	return xxx_messageInfo_Ok.Size(m)
}
func (m *Ok) XXX_DiscardUnknown() {
	xxx_messageInfo_Ok.DiscardUnknown(m)
}

var xxx_messageInfo_Ok proto.InternalMessageInfo

func (m *Ok) GetStarter() int32 {
	if m != nil {
		return m.Starter
	}
	return 0
}

func (m *Ok) GetDelay() float32 {
	if m != nil {
		return m.Delay
	}
	return 0
}

type Coordinator struct {
	Coordinator          int32    `protobuf:"varint,1,opt,name=coordinator,proto3" json:"coordinator,omitempty"`
	Delay                float32  `protobuf:"fixed32,2,opt,name=delay,proto3" json:"delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinator) Reset()         { *m = Coordinator{} }
func (m *Coordinator) String() string { return proto.CompactTextString(m) }
func (*Coordinator) ProtoMessage()    {}
func (*Coordinator) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e2dc367da0f1a31, []int{5}
}

func (m *Coordinator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinator.Unmarshal(m, b)
}
func (m *Coordinator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinator.Marshal(b, m, deterministic)
}
func (m *Coordinator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinator.Merge(m, src)
}
func (m *Coordinator) XXX_Size() int {
	return xxx_messageInfo_Coordinator.Size(m)
}
func (m *Coordinator) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinator.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinator proto.InternalMessageInfo

func (m *Coordinator) GetCoordinator() int32 {
	if m != nil {
		return m.Coordinator
	}
	return 0
}

func (m *Coordinator) GetDelay() float32 {
	if m != nil {
		return m.Delay
	}
	return 0
}

type Heartbeat struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Delay                float32  `protobuf:"fixed32,2,opt,name=delay,proto3" json:"delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e2dc367da0f1a31, []int{6}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Heartbeat) GetDelay() float32 {
	if m != nil {
		return m.Delay
	}
	return 0
}

type NodeList struct {
	List                 []*Node  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeList) Reset()         { *m = NodeList{} }
func (m *NodeList) String() string { return proto.CompactTextString(m) }
func (*NodeList) ProtoMessage()    {}
func (*NodeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e2dc367da0f1a31, []int{7}
}

func (m *NodeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeList.Unmarshal(m, b)
}
func (m *NodeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeList.Marshal(b, m, deterministic)
}
func (m *NodeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeList.Merge(m, src)
}
func (m *NodeList) XXX_Size() int {
	return xxx_messageInfo_NodeList.Size(m)
}
func (m *NodeList) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeList.DiscardUnknown(m)
}

var xxx_messageInfo_NodeList proto.InternalMessageInfo

func (m *NodeList) GetList() []*Node {
	if m != nil {
		return m.List
	}
	return nil
}

type NONE struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NONE) Reset()         { *m = NONE{} }
func (m *NONE) String() string { return proto.CompactTextString(m) }
func (*NONE) ProtoMessage()    {}
func (*NONE) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e2dc367da0f1a31, []int{8}
}

func (m *NONE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NONE.Unmarshal(m, b)
}
func (m *NONE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NONE.Marshal(b, m, deterministic)
}
func (m *NONE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NONE.Merge(m, src)
}
func (m *NONE) XXX_Size() int {
	return xxx_messageInfo_NONE.Size(m)
}
func (m *NONE) XXX_DiscardUnknown() {
	xxx_messageInfo_NONE.DiscardUnknown(m)
}

var xxx_messageInfo_NONE proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Node)(nil), "bully.Node")
	proto.RegisterType((*NodeAddr)(nil), "bully.NodeAddr")
	proto.RegisterType((*NodeId)(nil), "bully.NodeId")
	proto.RegisterType((*Election)(nil), "bully.Election")
	proto.RegisterType((*Ok)(nil), "bully.Ok")
	proto.RegisterType((*Coordinator)(nil), "bully.Coordinator")
	proto.RegisterType((*Heartbeat)(nil), "bully.Heartbeat")
	proto.RegisterType((*NodeList)(nil), "bully.NodeList")
	proto.RegisterType((*NONE)(nil), "bully.NONE")
}

func init() { proto.RegisterFile("node/protonode.proto", fileDescriptor_4e2dc367da0f1a31) }

var fileDescriptor_4e2dc367da0f1a31 = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x6b, 0x1a, 0x41,
	0x14, 0xc5, 0xcd, 0x6a, 0xf4, 0x2e, 0xc6, 0x70, 0xc9, 0xc3, 0x12, 0x0a, 0x95, 0x2d, 0x85, 0x25,
	0x01, 0x6d, 0x6d, 0xfb, 0xd2, 0x87, 0x82, 0x69, 0x6d, 0x2a, 0x94, 0x5d, 0x58, 0x0a, 0x85, 0xbe,
	0x8d, 0xce, 0x54, 0x27, 0x0e, 0x33, 0x32, 0x3b, 0xd2, 0xe4, 0xff, 0xf5, 0x87, 0x95, 0x19, 0x57,
	0x1d, 0x35, 0x21, 0xf4, 0xed, 0x7e, 0x9c, 0x73, 0x76, 0xf6, 0x1c, 0x66, 0xe0, 0x42, 0x2a, 0xca,
	0xfa, 0x4b, 0xad, 0x8c, 0xb2, 0x55, 0xcf, 0x55, 0x58, 0x9f, 0xac, 0x84, 0x78, 0x48, 0xee, 0x20,
	0xcc, 0x14, 0x65, 0x78, 0x06, 0x01, 0xa7, 0x71, 0xad, 0x5b, 0x4b, 0xeb, 0x45, 0xc0, 0x29, 0x22,
	0x84, 0x73, 0x55, 0x9a, 0x38, 0xe8, 0xd6, 0xd2, 0x56, 0xe1, 0x6a, 0x3b, 0x5b, 0x2a, 0x6d, 0xe2,
	0x13, 0x87, 0x72, 0x35, 0x5e, 0xc1, 0x39, 0x99, 0x9a, 0x15, 0x11, 0x19, 0xbb, 0x37, 0x5f, 0x09,
	0x17, 0x8c, 0xc6, 0x61, 0xb7, 0x96, 0x36, 0x8b, 0xa3, 0x79, 0x32, 0x80, 0xa6, 0xfd, 0xd6, 0x90,
	0x52, 0xbd, 0xd5, 0xaf, 0x3d, 0xa2, 0x1f, 0xec, 0xf4, 0x93, 0x18, 0x1a, 0x96, 0x33, 0xa6, 0x87,
	0x27, 0x4c, 0x3e, 0x42, 0x73, 0x24, 0xd8, 0xd4, 0x70, 0x25, 0x31, 0x86, 0xd3, 0xd2, 0x10, 0x6d,
	0x98, 0xae, 0x00, 0x9b, 0x16, 0x2f, 0xa0, 0x4e, 0x99, 0x20, 0x0f, 0x4e, 0x34, 0x28, 0xd6, 0x4d,
	0xf2, 0x1e, 0x82, 0x7c, 0xf1, 0xdf, 0xac, 0x11, 0x44, 0x9f, 0x95, 0xd2, 0x94, 0x4b, 0x62, 0x94,
	0xc6, 0x2e, 0x44, 0xd3, 0x5d, 0x5b, 0x49, 0xf8, 0xa3, 0x27, 0x64, 0xde, 0x42, 0xeb, 0x1b, 0x23,
	0xda, 0x4c, 0x18, 0x31, 0x47, 0xbe, 0x3f, 0x4e, 0xb9, 0x5e, 0x3b, 0xf7, 0x9d, 0x97, 0x06, 0x5f,
	0x42, 0x28, 0xb8, 0x73, 0xee, 0x24, 0x8d, 0x06, 0x51, 0xcf, 0xe5, 0xd8, 0xb3, 0xeb, 0xc2, 0x2d,
	0x92, 0x06, 0x84, 0x59, 0x9e, 0x8d, 0x06, 0x7f, 0x43, 0x68, 0x7e, 0xe1, 0xa5, 0xb9, 0xd5, 0x6c,
	0x89, 0x29, 0x34, 0xef, 0x14, 0x97, 0x05, 0x97, 0x33, 0xec, 0x78, 0x1c, 0x1b, 0xc6, 0xa5, 0x2f,
	0x82, 0xaf, 0xe1, 0x74, 0xc6, 0x8c, 0x2b, 0xdb, 0xde, 0x7c, 0x4c, 0xf7, 0x61, 0x6f, 0x00, 0x2d,
	0x8c, 0xdd, 0x9b, 0x62, 0x25, 0x25, 0x97, 0xb3, 0x67, 0x19, 0x7d, 0xe8, 0xfc, 0x56, 0xfa, 0x0f,
	0xd1, 0x74, 0x9b, 0xdb, 0xe6, 0x24, 0x9b, 0xc1, 0x8e, 0x90, 0x67, 0x23, 0x7c, 0x05, 0xad, 0x8a,
	0x90, 0x2f, 0xb0, 0x55, 0x6d, 0xf2, 0xc5, 0x3e, 0xe8, 0x03, 0x60, 0x05, 0xf2, 0xb3, 0xc1, 0x0a,
	0xe2, 0xcd, 0xf6, 0x69, 0x3d, 0x68, 0x97, 0x4c, 0x52, 0x17, 0xc4, 0x8d, 0x0d, 0xe2, 0xbc, 0xda,
	0x6e, 0xa3, 0xd9, 0xc7, 0x5f, 0x43, 0x34, 0x63, 0x66, 0x28, 0x84, 0xfd, 0x95, 0x12, 0xfd, 0xdd,
	0xa5, 0xef, 0xa7, 0x8b, 0x68, 0xe0, 0xbc, 0x19, 0x0a, 0xe1, 0x59, 0xf3, 0x1c, 0xe7, 0x13, 0xbc,
	0xf0, 0x3e, 0xf0, 0x93, 0x9b, 0xf9, 0x98, 0xde, 0x6a, 0x46, 0x0c, 0xd3, 0x3f, 0xe6, 0x44, 0x1e,
	0x3a, 0x7b, 0xc4, 0xbf, 0x82, 0x33, 0xcd, 0xec, 0x95, 0x19, 0x96, 0xeb, 0xeb, 0x86, 0xbe, 0xf9,
	0x87, 0x3f, 0xd3, 0xd9, 0x60, 0xab, 0x13, 0x3e, 0x0d, 0xbe, 0xe9, 0xfc, 0x6a, 0xbb, 0xae, 0xbf,
	0x9c, 0xf4, 0xed, 0xfb, 0x31, 0x69, 0xb8, 0x07, 0xe4, 0xdd, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x0e, 0x13, 0x2e, 0x83, 0x58, 0x04, 0x00, 0x00,
}
