// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serviceRegistry/protoserviceRegistry.proto

package serviceRegistry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Node struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	ActualNextFailed     bool     `protobuf:"varint,4,opt,name=actualNextFailed,proto3" json:"actualNextFailed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_be1a0bbcee78985c, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Node) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Node) GetActualNextFailed() bool {
	if m != nil {
		return m.ActualNextFailed
	}
	return false
}

type NodeAddr struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeAddr) Reset()         { *m = NodeAddr{} }
func (m *NodeAddr) String() string { return proto.CompactTextString(m) }
func (*NodeAddr) ProtoMessage()    {}
func (*NodeAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_be1a0bbcee78985c, []int{1}
}

func (m *NodeAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeAddr.Unmarshal(m, b)
}
func (m *NodeAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeAddr.Marshal(b, m, deterministic)
}
func (m *NodeAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeAddr.Merge(m, src)
}
func (m *NodeAddr) XXX_Size() int {
	return xxx_messageInfo_NodeAddr.Size(m)
}
func (m *NodeAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeAddr.DiscardUnknown(m)
}

var xxx_messageInfo_NodeAddr proto.InternalMessageInfo

func (m *NodeAddr) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *NodeAddr) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type NodeId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeId) Reset()         { *m = NodeId{} }
func (m *NodeId) String() string { return proto.CompactTextString(m) }
func (*NodeId) ProtoMessage()    {}
func (*NodeId) Descriptor() ([]byte, []int) {
	return fileDescriptor_be1a0bbcee78985c, []int{2}
}

func (m *NodeId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeId.Unmarshal(m, b)
}
func (m *NodeId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeId.Marshal(b, m, deterministic)
}
func (m *NodeId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeId.Merge(m, src)
}
func (m *NodeId) XXX_Size() int {
	return xxx_messageInfo_NodeId.Size(m)
}
func (m *NodeId) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeId.DiscardUnknown(m)
}

var xxx_messageInfo_NodeId proto.InternalMessageInfo

func (m *NodeId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type NodeList struct {
	List                 []*Node  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeList) Reset()         { *m = NodeList{} }
func (m *NodeList) String() string { return proto.CompactTextString(m) }
func (*NodeList) ProtoMessage()    {}
func (*NodeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_be1a0bbcee78985c, []int{3}
}

func (m *NodeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeList.Unmarshal(m, b)
}
func (m *NodeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeList.Marshal(b, m, deterministic)
}
func (m *NodeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeList.Merge(m, src)
}
func (m *NodeList) XXX_Size() int {
	return xxx_messageInfo_NodeList.Size(m)
}
func (m *NodeList) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeList.DiscardUnknown(m)
}

var xxx_messageInfo_NodeList proto.InternalMessageInfo

func (m *NodeList) GetList() []*Node {
	if m != nil {
		return m.List
	}
	return nil
}

type NONE struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NONE) Reset()         { *m = NONE{} }
func (m *NONE) String() string { return proto.CompactTextString(m) }
func (*NONE) ProtoMessage()    {}
func (*NONE) Descriptor() ([]byte, []int) {
	return fileDescriptor_be1a0bbcee78985c, []int{4}
}

func (m *NONE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NONE.Unmarshal(m, b)
}
func (m *NONE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NONE.Marshal(b, m, deterministic)
}
func (m *NONE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NONE.Merge(m, src)
}
func (m *NONE) XXX_Size() int {
	return xxx_messageInfo_NONE.Size(m)
}
func (m *NONE) XXX_DiscardUnknown() {
	xxx_messageInfo_NONE.DiscardUnknown(m)
}

var xxx_messageInfo_NONE proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Node)(nil), "bully.Node")
	proto.RegisterType((*NodeAddr)(nil), "bully.NodeAddr")
	proto.RegisterType((*NodeId)(nil), "bully.NodeId")
	proto.RegisterType((*NodeList)(nil), "bully.NodeList")
	proto.RegisterType((*NONE)(nil), "bully.NONE")
}

func init() {
	proto.RegisterFile("serviceRegistry/protoserviceRegistry.proto", fileDescriptor_be1a0bbcee78985c)
}

var fileDescriptor_be1a0bbcee78985c = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xd1, 0x6a, 0xfa, 0x30,
	0x14, 0xc6, 0x69, 0xad, 0xfe, 0xfb, 0x3f, 0x32, 0x1d, 0xe7, 0xaa, 0xf4, 0x66, 0x52, 0x18, 0x14,
	0x05, 0x1d, 0xdd, 0x13, 0x74, 0xcc, 0x0d, 0x61, 0x54, 0xc8, 0xe5, 0xee, 0xd4, 0x84, 0x2e, 0x12,
	0xda, 0x92, 0xc4, 0xa1, 0x4f, 0xb8, 0xd7, 0x1a, 0x89, 0x9b, 0xcb, 0xba, 0x0d, 0xef, 0x4e, 0xbe,
	0xf3, 0x7d, 0xbf, 0x73, 0xd2, 0x06, 0xc6, 0x8a, 0xc9, 0x57, 0xbe, 0x61, 0x84, 0x95, 0x5c, 0x69,
	0x79, 0x98, 0x35, 0xb2, 0xd6, 0x75, 0x4b, 0x9c, 0x5a, 0x11, 0xbb, 0xeb, 0x9d, 0x10, 0x87, 0x64,
	0x0b, 0x41, 0x51, 0x53, 0x86, 0x03, 0xf0, 0x39, 0x8d, 0xbc, 0x91, 0x97, 0x76, 0x89, 0xcf, 0x29,
	0x22, 0x04, 0x2f, 0xb5, 0xd2, 0x91, 0x3f, 0xf2, 0xd2, 0xff, 0xc4, 0xd6, 0x46, 0x6b, 0x6a, 0xa9,
	0xa3, 0x8e, 0x75, 0xd9, 0x1a, 0xc7, 0x70, 0xb9, 0xda, 0xe8, 0xdd, 0x4a, 0x14, 0x6c, 0xaf, 0x1f,
	0x56, 0x5c, 0x30, 0x1a, 0x05, 0x23, 0x2f, 0x0d, 0xc9, 0x0f, 0x3d, 0xc9, 0x20, 0x34, 0xb3, 0x72,
	0x4a, 0xe5, 0x89, 0xef, 0xfd, 0xc2, 0xf7, 0xbf, 0xf8, 0x49, 0x04, 0x3d, 0x93, 0x59, 0xd0, 0xf6,
	0x86, 0xc9, 0xe4, 0x48, 0x7b, 0xe2, 0x4a, 0xe3, 0x15, 0x04, 0x82, 0x5b, 0x5a, 0x27, 0xed, 0x67,
	0xfd, 0xa9, 0xbd, 0xdb, 0xd4, 0xb4, 0x89, 0x6d, 0x24, 0x3d, 0x08, 0x8a, 0x65, 0x31, 0xcf, 0xde,
	0x7c, 0x08, 0xef, 0xb9, 0xd2, 0x8f, 0x92, 0x35, 0x98, 0x42, 0xb8, 0xad, 0x79, 0x45, 0x78, 0x55,
	0xe2, 0xd0, 0xc9, 0x98, 0x05, 0x63, 0x17, 0x82, 0xd7, 0xf0, 0xaf, 0x64, 0xda, 0x96, 0x17, 0x8e,
	0xbe, 0xa0, 0xdf, 0x6d, 0x37, 0x80, 0xc6, 0xc6, 0xf6, 0x9a, 0xec, 0xaa, 0x8a, 0x57, 0xe5, 0xd9,
	0xc4, 0x04, 0xfa, 0x25, 0xd3, 0xb9, 0x10, 0xe6, 0xa4, 0xf0, 0xd4, 0x5b, 0x16, 0xf3, 0xd8, 0x5d,
	0xc9, 0xde, 0x32, 0xb3, 0xf8, 0x5c, 0x08, 0x87, 0x7e, 0x2e, 0x33, 0x86, 0x81, 0x64, 0xe6, 0x4b,
	0xe6, 0xea, 0xf8, 0x17, 0xd0, 0x9d, 0x1f, 0xbb, 0x61, 0x9c, 0xc0, 0xf0, 0xd3, 0xfb, 0x31, 0xe1,
	0x6f, 0xf3, 0x5d, 0xfc, 0x1c, 0xd9, 0xd3, 0xac, 0x59, 0xcf, 0x5a, 0x2f, 0x6c, 0xdd, 0xb3, 0x4f,
	0xec, 0xf6, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xe1, 0x41, 0x98, 0x90, 0x02, 0x00, 0x00,
}
