---
- hosts: all
  tasks:
    # reset the environment
    - name: teardown
      become: true
      shell: |
        rm -rf $HOME/distributed-election $HOME/.docker
        mkdir -p $HOME/.docker/cli-plugins
        
    # install dependencies    
    - name: install git
      become: true
      yum:
         name: git
         state: present
         update_cache: true
             
    - name: install docker
      become: true
      yum:
         name: docker
         state: present
         update_cache: true

    - name: install docker-compose plugin
      become: true
      shell: |
        curl -SL https://github.com/docker/compose/releases/download/v2.11.1/docker-compose-linux-x86_64 -o $HOME/.docker/cli-plugins/docker-compose
        chmod +x -R $HOME/.docker/cli-plugins/docker-compose

    - name: clone project repository
      shell: |
        git clone https://github.com/massimostanzione/distributed-election.git
        chmod -R 777 /home/ec2-user/distributed-election

    # setup docker service
    - name: enable docker.service
      become: true
      systemd:
        name: docker.service
        daemon_reload: true
        state: restarted
        enabled: true
        
    - name: docker.sock permission
      become: true
      ansible.builtin.command:
        cmd: "chmod 666 /var/run/docker.sock"
       
    # setup project service
    - name: copy systemd unit file
      become: true
      copy:
           src: "app.service"
           dest: "/etc/systemd/system/"
           
    - name: app.service permission
      become: true
      ansible.builtin.command:
        cmd: "chmod 777 /etc/systemd/system/app.service"

    - name: restart systemd service
      become: true
      systemd:
           daemon_reload: true
           state: restarted
           name: "app.service"
           enabled: true
